export const ACCOUNT_TIERS = [
  {
    size: 5000,
    label: '$5,000',
    title: 'Starter Trader',
    badge: 'Tier 1',
    description: 'Perfect for beginners looking to prove consistency and build discipline.',
    profitTarget: 8,
    dailyDrawdown: 5,
    maxDrawdown: 10,
    minTradingDays: 3,
    inactivityLimit: 15,
    recommended: false,
  },
  {
    size: 10000,
    label: '$10,000',
    title: 'Standard Trader',
    badge: 'Popular',
    description: 'Standard simulated funded account to build strong risk management skills.',
    profitTarget: 8,
    dailyDrawdown: 5,
    maxDrawdown: 10,
    minTradingDays: 3,
    inactivityLimit: 15,
    recommended: true,
  },
  {
    size: 25000,
    label: '$25,000',
    title: 'Advanced Trader',
    badge: 'Pro',
    description: 'Generous capital allocation for experienced technical and swing traders.',
    profitTarget: 8,
    dailyDrawdown: 5,
    maxDrawdown: 10,
    minTradingDays: 3,
    inactivityLimit: 15,
    recommended: false,
  },
  {
    size: 50000,
    label: '$50,000',
    title: 'Expert Trader',
    badge: 'Elite',
    description: 'Scale up your position sizes with high capital flexibility and strict rules.',
    profitTarget: 8,
    dailyDrawdown: 5,
    maxDrawdown: 10,
    minTradingDays: 3,
    inactivityLimit: 15,
    recommended: false,
  },
  {
    size: 100000,
    label: '$100,000',
    title: 'Master Trader',
    badge: 'Institutional',
    description: 'Institutional simulated trading size for top-performing disciplined traders.',
    profitTarget: 8,
    dailyDrawdown: 5,
    maxDrawdown: 10,
    minTradingDays: 3,
    inactivityLimit: 15,
    recommended: false,
  }
];

export const SUPPORTED_PAIRS = [
  { value: 'EURUSD', label: 'EUR / USD', category: 'Forex Major', pipSize: 0.0001, defaultPrice: 1.0850 },
  { value: 'GBPUSD', label: 'GBP / USD', category: 'Forex Major', pipSize: 0.0001, defaultPrice: 1.2950 },
  { value: 'USDJPY', label: 'USD / JPY', category: 'Forex Major', pipSize: 0.01, defaultPrice: 152.40 },
  { value: 'GBPJPY', label: 'GBP / JPY', category: 'Forex Cross', pipSize: 0.01, defaultPrice: 196.20 },
  { value: 'XAUUSD', label: 'XAU / USD (Gold)', category: 'Commodity', pipSize: 0.01, defaultPrice: 2650.00 },
  { value: 'XAGUSD', label: 'XAG / USD (Silver)', category: 'Commodity', pipSize: 0.01, defaultPrice: 31.50 },
  { value: 'BTCUSD', label: 'BTC / USD (Bitcoin)', category: 'Crypto', pipSize: 0.1, defaultPrice: 68500.00 },
  { value: 'ETHUSD', label: 'ETH / USD (Ethereum)', category: 'Crypto', pipSize: 0.1, defaultPrice: 2550.00 },
];

export const CHALLENGE_STATUS = {
  NOT_STARTED: 'Not-Started',
  ACTIVE: 'Active',
  PASSED: 'Passed',
  FAILED: 'Failed',
  INACTIVE: 'Inactive',
};

export const STATUS_CONFIG = {
  'Active': {
    label: 'ACTIVE',
    bg: 'bg-emerald-50',
    border: 'border-emerald-200',
    text: 'text-emerald-700',
    dot: 'bg-emerald-500',
    glow: 'shadow-sm',
  },
  'Not-Started': {
    label: 'NOT STARTED',
    bg: 'bg-slate-100',
    border: 'border-slate-200',
    text: 'text-slate-600',
    dot: 'bg-slate-400',
    glow: '',
  },
  'Passed': {
    label: 'PASSED',
    bg: 'bg-blue-50',
    border: 'border-blue-200',
    text: 'text-blue-700',
    dot: 'bg-blue-600',
    glow: 'shadow-sm',
  },
  'Failed': {
    label: 'FAILED',
    bg: 'bg-rose-50',
    border: 'border-rose-200',
    text: 'text-rose-700',
    dot: 'bg-rose-500',
    glow: 'shadow-sm',
  },
  'Inactive': {
    label: 'INACTIVE',
    bg: 'bg-amber-50',
    border: 'border-amber-200',
    text: 'text-amber-700',
    dot: 'bg-amber-500',
    glow: 'shadow-sm',
  }
};
